### ISSUE TITLE
Uninitialized read

### ISSUE THREAD

**Issue by PerilousApricot** [accre/lstore#101]
In lio/os_file.c, it_top can be uninitialized here:

https://github.com/accre/lstore/blob/master/src/lio/os_file.c#L1616

if this "if" statement takes the false branch here:

https://github.com/accre/lstore/blob/master/src/lio/os_file.c#L1515

I'm having trouble grokking this really long, really-deeply-nested function to see if that even makes sense. Perhaps @tacketar can decrypt it.

**Comment by tacketar** [comment]
At first glance this looks like a false positive.  Notice that if 
*prefix_len == 0 then it_top should be non-NULL and points to the 
current stack top containing the search prefix.  This is all done before 
going into the recursion loops.  And if the value of *prefix_len is 
changed it's followed by a return() call.  So *prefix_len is acting to 
protect referencing a NULL it_top.

**Comment by PerilousApricot** [comment]
Hmm. I'll have to stare at it some more... Let's try and write more concise functions. This guy nests _12_ levels deep :smile:
