### ISSUE TITLE
Generate -debug/-dbg packages

### ISSUE THREAD

**Issue by PerilousApricot** [accre/lstore#12]
RPM at least has a simple addition to the .spec file which can be used to make a `-debug` package. While doing that, it strips the other binaries, making them much smaller. CPack, unfortunately, doesn't natively support adding that one line. There's two options:
- Call CPack in 2 phases: One to generate the spec it _would_ use, perform surgery to add the appropriate stanzas, then call cpack again with the newly-modified spec
- Bring our own patched CPackRPM.cmake, modified to support this use case

I have no idea how .deb would do it.

**Comment by PerilousApricot** [comment]
The RPM half fixed by #47. Deb part solved in #54.

**Comment by hellermf** [comment]
Once PR 54 is merged is there anything more we need to do before we consider this issue closed?

**Comment by PerilousApricot** [comment]
AFAIK, it Does The Right Thing. Once this goes in, I'll change over the jenkins packaging to use the unified one

**Comment by PerilousApricot** [comment]
Fixed by #47/#54
